language: php

php:
  - hhvm
  - hhvm-nightly

matrix:
  allow_failures:
    - php: hhvm-nightly

services:
  - memcached
  - redis-server

script:
  - vendor/bin/phpunit

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --prefer-source --dev

notifications:
  email: false
